package com.danielasfregola.twitter4s.entities.enums

object Language extends Enumeration {
  type Language = Value

  val English = Value("en")
  val Arabic = Value("ar")
  val Bengali = Value("bn")
  val Czech = Value("cs")
  val Danish = Value("da")
  val German = Value("de")
  val Greek = Value("el")
  val Spanish = Value("es")
  val Persian = Value("fa")
  val Finnish = Value("fi")
  val Filipino = Value("fil")
  val French = Value("fr")
  val Hebrew = Value("he")
  val Hindi = Value("hi")
  val Hungarian = Value("hu")
  val Indonesian = Value("id")
  val Italian = Value("it")
  val Japanese = Value("ja")
  val Korean = Value("ko")
  val Malay = Value("msa")
  val Dutch = Value("nl")
  val Norwegian = Value("no")
  val Polish = Value("pl")
  val Portuguese = Value("pt")
  val Romanian = Value("ro")
  val Russian = Value("ru")
  val Swedish = Value("sv")
  val Thai = Value("th")
  val Turkish = Value("tr")
  val Ukrainian = Value("uk")
  val Urdu = Value("ur")
  val Vietnamese = Value("vi")
  val ChineseSimplified = Value("zh-cn")
  val Chinese = Value("zh-tw")
}
