package com.danielasfregola.twitter4s.entities

import java.time.Instant

final case class User(blocked_by: Boolean = false,
                      blocking: Boolean = false,
                      contributors_enabled: Boolean = false,
                      created_at: Instant,
                      default_profile: Boolean = false,
                      default_profile_image: Boolean = false,
                      description: Option[String] = None,
                      email: Option[String] = None,
                      entities: Option[Entities] = None,
                      favourites_count: Int,
                      follow_request_sent: Boolean = false,
                      following: Boolean = false,
                      followers_count: Int,
                      friends_count: Int,
                      geo_enabled: Boolean = false,
                      has_extended_profile: Boolean = false,
                      id: Long,
                      id_str: String,
                      is_translation_enabled: Boolean = false,
                      is_translator: Boolean = false,
                      lang: String,
                      listed_count: Int,
                      location: Option[String] = None,
                      muting: Boolean = false,
                      name: String,
                      notifications: Boolean = false,
                      profile_background_color: String,
                      profile_background_image_url: String,
                      profile_background_image_url_https: String,
                      profile_background_tile: Boolean = false,
                      profile_banner_url: Option[String] = None,
                      profile_image_url: ProfileImage,
                      profile_image_url_https: ProfileImage,
                      profile_link_color: String,
                      profile_location: Option[String],
                      profile_sidebar_border_color: String,
                      profile_sidebar_fill_color: String,
                      profile_text_color: String,
                      profile_use_background_image: Boolean = false,
                      `protected`: Boolean = false,
                      screen_name: String,
                      show_all_inline_media: Boolean = false,
                      status: Option[Tweet] = None,
                      statuses_count: Int,
                      time_zone: Option[String] = None,
                      translator_type: Option[String] = None,
                      url: Option[String] = None,
                      utc_offset: Option[Int] = None,
                      verified: Boolean = false,
                      withheld_in_countries: Option[String] = None,
                      withheld_scope: Option[String] = None)
