package twitter4s.entities.enums

object TimeZone extends Enumeration {
  type TimeZone = Value

  val Africa_Algiers  = Value("Africa/Algiers")
  val Africa_Cairo  = Value("Africa/Cairo")
  val Africa_Casablanca  = Value("Africa/Casablanca")
  val Africa_Harare  = Value("Africa/Harare")
  val Africa_Johannesburg  = Value("Africa/Johannesburg")
  val Africa_Monrovia  = Value("Africa/Monrovia")

  val America_Chihuahua  = Value("America/Chihuahua")
  val America_Denver  = Value("America/Denver")
  val America_Juneau  = Value("America/Juneau")
  val America_Los_Angeles  = Value("America/Los_Angeles")
  val America_Phoenix  = Value("America/Phoenix")
  val America_Tijuana  = Value("America/Tijuana")
  val America_Mazatlan  = Value("America/Mazatlan")
  val America_Chicago  = Value("America/Chicago")
  val America_Regina  = Value("America/Regina")
  val America_Mexico_City  = Value("America/Mexico_City")
  val America_Monterrey  = Value("America/Monterrey")
  val America_Guatemala  = Value("America/Guatemala")
  val America_New_York  = Value("America/New_York")
  val America_Indiana_Indianapolis  = Value("America/Indiana_Indianapolis")
  val America_Bogota  = Value("America/Bogota")
  val America_Lima  = Value("America/Lima")
  val America_Halifax  = Value("America/Halifax")
  val America_Caracas  = Value("America/Caracas")
  val America_La_Paz  = Value("America/La_Paz")
  val America_Santiago  = Value("America/Santiago")
  val America_St_Johns  = Value("America/St_Johns")
  val America_Sao_Paulo  = Value("America/Sao_Paulo")
  val America_Argentina_Buenos_Aires  = Value("America/Argentina_Buenos_Aires")
  val America_Montevideo  = Value("America/Montevideo")
  val America_Guyana  = Value("America/Guyana")
  val America_Godthab  = Value("America/Godthab")

  val Asia_Jerusalem  = Value("Asia/Jerusalem")
  val Asia_Kuwait  = Value("Asia/Kuwait")
  val Asia_Riyadh  = Value("Asia/Riyadh")
  val Africa_Nairobi  = Value("Africa/Nairobi")
  val Asia_Baghdad  = Value("Asia/Baghdad")
  val Asia_Tehran  = Value("Asia/Tehran")
  val Asia_Muscat  = Value("Asia/Muscat")
  val Asia_Baku  = Value("Asia/Baku")
  val Asia_Tbilisi  = Value("Asia/Tbilisi")
  val Asia_Yerevan  = Value("Asia/Yerevan")
  val Asia_Kabul  = Value("Asia/Kabul")
  val Asia_Yekaterinburg  = Value("Asia/Yekaterinburg")
  val Asia_Karachi  = Value("Asia/Karachi")
  val Asia_Tashkent  = Value("Asia/Tashkent")
  val Asia_Kolkata  = Value("Asia/Kolkata")
  val Asia_Kathmandu  = Value("Asia/Kathmandu")
  val Asia_Dhaka  = Value("Asia/Dhaka")
  val Asia_Colombo  = Value("Asia/Colombo")
  val Asia_Almaty  = Value("Asia/Almaty")
  val Asia_Novosibirsk  = Value("Asia/Novosibirsk")
  val Asia_Rangoon  = Value("Asia/Rangoon")
  val Asia_Bangkok  = Value("Asia/Bangkok")
  val Asia_Jakarta  = Value("Asia/Jakarta")
  val Asia_Krasnoyarsk  = Value("Asia/Krasnoyarsk")
  val Asia_Shanghai  = Value("Asia/Shanghai")
  val Asia_Chongqing  = Value("Asia/Chongqing")
  val Asia_Hong_Kong  = Value("Asia/Hong_Kong")
  val Asia_Urumqi  = Value("Asia/Urumqi")
  val Asia_Kuala_Lumpur  = Value("Asia/Kuala_Lumpur")
  val Asia_Singapore  = Value("Asia/Singapore")
  val Asia_Taipei  = Value("Asia/Taipei")
  val Australia_Perth  = Value("Australia_Perth")
  val Asia_Irkutsk  = Value("Asia/Irkutsk")
  val Asia_Ulaanbaatar  = Value("Asia/Ulaanbaatar")
  val Asia_Seoul  = Value("Asia/Seoul")
  val Asia_Tokyo  = Value("Asia/Tokyo")
  val Asia_Yakutsk  = Value("Asia/Yakutsk")
  val Asia_Vladivostok  = Value("Asia/Vladivostok")
  val Asia_Magadan  = Value("Asia/Magadan")
  val Asia_Srednekolymsk  = Value("Asia/Srednekolymsk")
  val Asia_Kamchatka  = Value("Asia/Kamchatka")

  val Atlantic_Azores  = Value("Atlantic/Azores")
  val Atlantic_Cape_Verde  = Value("Atlantic/Cape_Verde")
  val Atlantic_South_Georgia  = Value("Atlantic/South_Georgia")

  val Australia_Adelaide  = Value("Australia_Adelaide")
  val Australia_Brisbane  = Value("Australia_Brisbane")
  val Australia_Darwin  = Value("Australia_Darwin")
  val Australia_Hobart  = Value("Australia_Hobart")
  val Australia_Melbourne  = Value("Australia_Melbourne")
  val Australia_Sydney  = Value("Australia_Sydney")

  val Etc_UTC  = Value("Etc_UTC")

  val Europe_Belgrade  = Value("Europe/Belgrade")
  val Europe_Bratislava  = Value("Europe/Bratislava")
  val Europe_Budapest  = Value("Europe/Budapest")
  val Europe_Dublin  = Value("Europe/Dublin")
  val Europe_Lisbon  = Value("Europe/Lisbon")
  val Europe_Ljubljana  = Value("Europe/Ljubljana")
  val Europe_London  = Value("Europe/London")
  val Europe_Prague  = Value("Europe/Prague")
  val Europe_Sarajevo  = Value("Europe/Sarajevo")
  val Europe_Skopje  = Value("Europe/Skopje")
  val Europe_Warsaw  = Value("Europe/Warsaw")
  val Europe_Zagreb  = Value("Europe/Zagreb")
  val Europe_Brussels  = Value("Europe/Brussels")
  val Europe_Copenhagen  = Value("Europe/Copenhagen")
  val Europe_Madrid  = Value("Europe/Madrid")
  val Europe_Paris  = Value("Europe/Paris")
  val Europe_Amsterdam  = Value("Europe/Amsterdam")
  val Europe_Berlin  = Value("Europe/Berlin")
  val Europe_Rome  = Value("Europe/Rome")
  val Europe_Stockholm  = Value("Europe/Stockholm")
  val Europe_Vienna  = Value("Europe/Vienna")
  val Europe_Bucharest  = Value("Europe/Bucharest")
  val Europe_Helsinki  = Value("Europe/Helsinki")
  val Europe_Kiev  = Value("Europe/Kiev")
  val Europe_Riga  = Value("Europe/Riga")
  val Europe_Sofia  = Value("Europe/Sofia")
  val Europe_Tallinn  = Value("Europe/Tallinn")
  val Europe_Vilnius  = Value("Europe/Vilnius")
  val Europe_Athens  = Value("Europe/Athens")
  val Europe_Istanbul  = Value("Europe/Istanbul")
  val Europe_Minsk  = Value("Europe/Minsk")
  val Europe_Kaliningrad  = Value("Europe/Kaliningrad")
  val Europe_Moscow  = Value("Europe/Moscow")
  val Europe_Volgograd  = Value("Europe/Volgograd")
  val Europe_Samara  = Value("Europe/Samara")

  val Pacific_Guadalcanal  = Value("Pacific/Guadalcanal")
  val Pacific_Noumea  = Value("Pacific/Noumea")
  val Pacific_Fiji  = Value("Pacific/Fiji")
  val Pacific_Guam  = Value("Pacific/Guam")
  val Pacific_Port_Moresby  = Value("Pacific/Port_Moresby")
  val Pacific_Majuro  = Value("Pacific/Majuro")
  val Pacific_Auckland  = Value("Pacific/Auckland")
  val Pacific_Tongatapu  = Value("Pacific/Tongatapu")
  val Pacific_Fakaofo  = Value("Pacific/Fakaofo")
  val Pacific_Chatham  = Value("Pacific/Chatham")
  val Pacific_Apia  = Value("Pacific/Apia")
  val Pacific_Midway = Value("Pacific/Midway")
  val Pacific_Pago_Pago = Value("Pacific/Pago_Pago")
  val Pacific_Honolulu = Value("Pacific/Honolulu")

 }

