package com.danielasfregola.twitter4s.entities.streaming

final case class StreamingUpdate(streamingEvent: StreamingMessage)

trait StreamingMessage

trait CommonStreamingMessage extends UserStreamingMessage with SiteStreamingMessage
trait UserStreamingMessage extends StreamingMessage
trait SiteStreamingMessage extends StreamingMessage
